# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3afc192860811d6a786f1417df5f24b024303e306ae33a36ceebb568610bb56311576026fc6041ca770bc734eba949311914632405fd958539ae31d4879e9349

test:
  secret_key_base: ad62b1acaf337c2a9f4f7c3b3c49cc529015b605a1d11afdd427678f86356e877b2708893a7a13b0778573ede71b7ed2ae40ea68f451d0ac3f6a48d1dbb58fc0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
